# Configurações de aplicação
spring:
  on-profiles: local
  application:
    name: sboot-ministerio-recomeco

# Configurações do servidor
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:8081/v1/api/ministerio-recomeco/token/login


# Configurações do Spring Security (se aplicável)
# security:
#   basic:
#     enabled: true
#   oauth2:
#     client:
#       registration:
#         google:
#           client-id: SeuClientID
#           client-secret: SeuClientSecret

---
# Configurações do banco de dados (se aplicável)
spring:
  on-profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/ministeriodb?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: R00Tr00t2020
